apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRESQL_DATABASE: app
  POSTGRESQL_USERNAME: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRESQL_PASSWORD: YWRtaW4=
  POSTGRESQL_POSTGRES_PASSWORD: YWRtaW4=
