apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: my-postgres-cluster
  namespace: postgres
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 2Gi
    storageClass: local-path
